version: '3'
services:
  mongo:
    image: "mongo:3.6.8-stretch"
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

  ejercicio:
    build: .
    depends_on:
      - mongo

    ports:
      - 3000:3000
    volumes:
      - ./:/ejercicio
      - /ejercicio/node_modules

volumes:
  mongo:
